default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nautica_dev

test:
  <<: *default
  database: nautica_test

production:
  <<: *default
  database: nautica_prod
