default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: database_development

test:
  <<: *default
  database: database_development

production:
  <<: *default
  database: database_development
